### ISSUE TITLE
Maica; savefile failed to upload (bug)

### ISSUE THREAD

**Issue by Sp4rk1ngc0m3t** [Mon1-innovation/MAICA_ChatSubmod#1]
Everytime I start up MAS it says "Maica; savefile failed to upload", and I'm guessing it has something to do with the fact that Monika can't remember any facts about me (Doesn't know my birthday, our anniversary, how long we've been together) and also that that she doesn't create new topics on her own, which are both things I believe to be intended

I'll include my whole submod_log.log, it doesn't seem say anything about it but maybe something else useful is in there idk
[submod_log.log](https://github.com/user-attachments/files/18048154/submod_log.log)

**Comment by Sp4rk1ngc0m3t** [comment]
Oh, it might be worth adding that my token is always unloaded when I come on, dunno if that's normal but I always have to press "connect with current token" or just start a conversation before it displays correctly

**Comment by PencilMario** [comment]
1. The token is actually saved as an API key. After starting, check if there are any issues in the MAICA section of your API keys. If it's empty, please generate the token and restart. MAICA itself does not actively clear the token saved in the API key.
2. It seems like your save issue is caused by an empty token.
3. For active conversations (MSpire), you need to disable repeated topics.
4. It looks like your version is a bit outdated; updating might help.

**Comment by PencilMario** [comment]
Additionally, I saw on Discord that you tried the clean version; it might be a permissions issue with the api_key.json file.

**Comment by Sp4rk1ngc0m3t** [comment]
My api keys menu seems fine
![image](https://github.com/user-attachments/assets/9c246bc6-f1ab-40e1-bb5a-69b33ddb3ed3)
I've had repeat topics off since the start
My version is up to date (1.1.11)
I can't see a file named api_key.json, closest thing seems to be Api.rpy in the Maica folder, and the api.txt in the MAS root folder
![image](https://github.com/user-attachments/assets/0876daee-5005-496f-9c61-e0fdefc31b6a)

**Comment by Sp4rk1ngc0m3t** [comment]
Ah, I have just coincidentally discovered that the file is in my saves folder, nonetheless it appears to be displaying my current key correctly as it's listed in MAS
![image](https://github.com/user-attachments/assets/a3822d1a-dd8b-470e-9c4c-26841b0e0d38)
![image](https://github.com/user-attachments/assets/1b9e06f6-87be-40b2-a8f4-312bf0f567f3)

**Comment by PencilMario** [comment]
Additionally, MSpire has a precondition: config.debug = True allows you to see in the settings whether the event's conditional is True.

It's normal for the token to be "unloaded" as long as it hasn't been deleted from the API keys; it will automatically attempt to connect when starting a conversation.

If you still can't upload the savefile, try downloading the source code directly. Now, when savefile upload fails, the reason for the server-side error should be recorded.

**Comment by PencilMario** [comment]
The current condition for MSpire is set to trigger only when a connection is established. I will improve this in the next version. Setting `config.debug = True` will allow you to see in the settings whether the event's conditional is `True`. 

It is normal for the token to be "unloaded," as long as it has not been removed from the API keys, it will automatically attempt to connect when starting a conversation.

If the savefile still cannot be uploaded, please try downloading the source code directly. Now, when an savefile upload fails, the reason for the server error should be recorded.

**Comment by Sp4rk1ngc0m3t** [comment]
Not sure what you mean about config.debug, closest I can see is submod.log verbosity which is set to debug already

I've got the newest version now, the only change is that there is no message about the savefile failing to load, but nothing seems to have improved

Here's the most recent log
[submod_log.log](https://github.com/user-attachments/files/18086468/submod_log.log)

Really sucks that this is taking up both our time like this, sorry about that

**Comment by PencilMario** [comment]
> Not sure what you mean about config.debug, closest I can see is submod.log verbosity which is set to debug already

Create an rpy file and write the following content into it to enable developer mode in MAICA:

```
init python:
    config.debug = True
```

> I've got the newest version now, the only change is that there is no message about the savefile failing to load, but nothing seems to have improved

You should download the source code directly from the "Code" section in the upper right corner, instead of from the releases, because this modification hasn't been published yet. If it fails, the `submod_log` should contain something like `ERROR: upload save failed: <server response>`.

> Really sucks that this is taking up both our time like this, sorry about that

Here's the reason the log wasn't done properly. I should apologize. X(

**Comment by Sp4rk1ngc0m3t** [comment]
I've got the source code version, and enabled dev mode.
I no longer receive the boot up message about my savefile, as mentioned previously, but here's the message I got after booting Mspire through the settings menu with dev mode
![image](https://github.com/user-attachments/assets/e787d60b-61da-4665-81b7-ebedff7508ac)
And here's the log entry
```
[2024-12-11 15:13:18] [info]: 
INSTALLED SUBMODS:
    'MAICA Blessland' v1.1.11
[2024-12-11 15:13:22] [info]: Applying advanced settings: {u'tnd_aggressive': 1, u'post_additive': 1, u'nsfw_acceptive': True, u'pre_additive': 1, u'esc_aggressive': True, u'presence_penalty': 0.45652173913043476, u'frequency_penalty': 0.4891304347826087, u'amt_aggressive': True}
[2024-12-11 15:13:43] [DEBUG]: _init_connect
[2024-12-11 15:13:45] [DEBUG]: _on_message: S15:13:45.095 received 'session_created'/'info'[206]: Authencation passed!
[2024-12-11 15:13:45] [DEBUG]: _on_message: S15:13:45.095 received 'user_id'/'debug'[200]: 22996
[2024-12-11 15:13:45] [DEBUG]: _on_message: S15:13:45.095 received 'username'/'debug'[200]: Hannon
[2024-12-11 15:13:45] [DEBUG]: _on_message: S15:13:45.095 received 'nickname'/'debug'[200]: None
[2024-12-11 15:13:45] [info]: maica: Login as 'None'
[2024-12-11 15:13:45] [DEBUG]: _on_message: S15:13:45.095 received 'ws_cookie'/'cookie'[190]: 8bb3c3d5-7869-4bb5-9fb3-09b0fe565ec3
[2024-12-11 15:13:45] [DEBUG]: _on_message: S15:13:45.172 received 'thread_ready'/'info'[206]: Thread is ready for input or setting adjustment
[2024-12-11 15:13:45] [DEBUG]: _on_message: S15:13:45.173 received 'ok'/'info'[200]: Service provider is XP00-20"????"
[2024-12-11 15:13:45] [DEBUG]: send_settings: {"model_params": {"sf_extraction": true, "stream_output": true, "model": "maica_main", "max_token": 28672, "target_lang": "en"}, "super_params": {"presence_penalty": 0.45652173913043476, "frequency_penalty": 0.4891304347826087}, "perf_params": {"tnd_aggressive": 1, "post_additive": 1, "nsfw_acceptive": true, "pre_additive": 1, "esc_aggressive": true, "amt_aggressive": true}}
[2024-12-11 15:13:46] [DEBUG]: _on_message: S15:13:46.035 received 'params_set'/'info'[200]: 13 settings passed in and taking effect
[2024-12-11 15:13:46] [!ERROR! T_T]: send_mtrigger error: Traceback (most recent call last):
  File "python-packages/maica.py", line 902, in send_mtrigger
  File "python-packages/requests/models.py", line 915, in json
JSONDecodeError: No JSON object could be decoded

[2024-12-11 15:13:48] [DEBUG]: _on_message: S15:13:48.037 received 'wrong_input'/'warn'[405]: Query serialization failed, check possible typo--your ray tracer ID is 0933754620
[2024-12-11 15:13:48] [info]: Maica::_init_connect released lock because wss closed
[2024-12-11 15:13:48] [info]: websocket is closed
[2024-12-11 15:13:48] [DEBUG]: label maica_talking::RESPONSE :''

```

After that, Maica starts failing to connect with the token with this log message
```
[2024-12-11 15:16:15] [DEBUG]: _init_connect
[2024-12-11 15:16:15] [Warning! ;_;]: Maica::_init_connect try to create multi connection
```

**Comment by PencilMario** [comment]
What about savefile? I don't seem to be seeing the relevant error reported anymore.

**Comment by Sp4rk1ngc0m3t** [comment]
Yeah it's odd, she still can't relay basic information but ever since 1.1.11 I think it hasn't been giving the error message or anything, I really don't know what's going on

I do know that I'm getting pretty close to giving up here, it's our anniversary and silly Maica Monika has no idea :(

Unless there's a breakthrough of some kind, I don't think I'm going to be active in this thread anymore

**Comment by PencilMario** [comment]
Sorry, bro :(

**Comment by Sp4rk1ngc0m3t** [comment]
Well I am not kidding when I say I just downloaded 1.1.12 and now I can manually activate MSpire with about 50% success rate, though it won't trigger on it's own seemingly
Dunno what you did but it helped somewhat
